version: '3.1'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 20118:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      LANG: C.UTF-8
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ~/tmp/docker_data/dsj/mysql:/var/lib/mysql